**File access**

The open() function takes two parameters; filename, and mode.

* file.close()
* file.read([size])
* file.readline([size])
* file.write()

There are four different methods (modes) for opening a file:

* "r" - Read - Default value. Opens a file for reading, error if the file does not exist
* "a" - Append - Opens a file for appending, creates the file if it does not exist
* "w" - Write - Opens a file for writing, creates the file if it does not exist
* "x" - Create - Creates the specified file, returns an error if the file exists

In [ ]:
# Create a file

f= open("demofile.txt", "w")
f.write("Line number one")
f.write("\n")
f.write("Line number two")
f.close()

In [ ]:
# Read file in different ways
f = open("demofile.txt", "r")
# use rb for 1 and 2 whence (2nd param) in seek. 0-start, 1- current pos, 2- EOF
print(type(f))

fl=f.read() #try with 20
print(type(fl))
print(len(fl))

#f.seek(0,0) # place file pointer wherever required. first param is offset
print(f.read()) # won't print anything till we open it again

<class '_io.BufferedReader'>
<class 'bytes'>
31
b'r two'

In [ ]:
f = open("demofile.txt", "r")
print(f.read(5))
print(f.read(5))

f = open("demofile.txt", "r")
print(f.readline())
print(f.readline(13))

f = open("demofile.txt", "r")
for x in f:
  print(x)

Line
numbe
Line number one

Line number t
Line number one

Line number two

In [ ]:
# Append data to file
f = open("demofile.txt", "a")
f.write("\nNow the file has more content")
f.close()

f = open("demofile.txt", "r")
print(f.read())

Line number one
Line number two
Now the file has more content
Now the file has more content

In [ ]:
import os # Operating System module
os.remove("demofile.txt")
# https://www.geeksforgeeks.org/os-module-python-examples/

Run this code only locally not in colab

* import sys
* old_target= sys.stdout

* sys.stdout = open('file', 'w')
* print('test')
* sys.stdout.close()

* sys.stdout = old_target

**Exception handling**

* An exception can be defined as an abnormal condition in a program resulting in the disruption in the flow of the program.

* Whenever an exception occurs, the program halts the execution, and thus further code is not executed. Therefore, an exception is the error which python script is unable to tackle with.

* Python provides us with the way to handle the Exception so that the other part of the code can be executed without any disruption.



---

* The **try** block lets you test a block of code for errors.

* The **except** block lets you handle the error.

* The **finally** block lets you execute code, regardless of the result of the try- and except blocks.

* You can use the **else** keyword to define a block of code to be executed if no errors were raised

In [ ]:
# without handling exceptions
a = 5
b = 0
c = a/b
print(c)

# next code:
print("Hi I am in next part of the program")

ZeroDivisionError: division by zero

In [ ]:
# handling exceptions
try:
    a = 5
    b = 0 # change it to 1 and see
    c = a/b
    print(c)
except:
    print("can't divide by zero")
else:
    print("Hi I am else block")

# next code:
print("Hi I am in next part of the program")

5.0
Hi I am else block
Hi I am in next part of the program

In [ ]:
# handling multiple exceptions
try:
    a = 5
    b = 0 # change it to 1 and see
    c = a/b
    print(c)
    #f=open('demofile.txt')
    d=e  # remove the comment and see
except ZeroDivisionError:
    print("can't divide by zero")
except NameError as ne:
    print("Name has a problem")
    print(ne)
except BaseException as ex:
    print("Some other problem")
    print(type(ex))
    print(ex)
else:
    print("Hi I am else block")

5.0
Some other problem
<class 'FileNotFoundError'>
[Errno 2] No such file or directory: 'demofile.txt'

In [ ]:
# using finally
try:
  print(5/0) #try with 5/0
except:
  print("Something went wrong")
finally:
  print("The 'try except' is finished")

Something went wrong
The 'try except' is finished

In [ ]:
# custom exceptions
class ErrorInCode(Exception):
    def __init__(self, data):
        self.data = data
    def custexp1(self):
      print('custexp1')
    def custexp2(self):
      print('custexp2')

try:
    raise ErrorInCode(2000)
except ErrorInCode as ae:
    if(ae.data==2000):
      ae.custexp1()
    if(ae.data==3000):
      ae.custexp2()

custexp1

**Data Access using SQLite**

In [ ]:
# Create table
import sqlite3
conn = sqlite3.connect('test.db')
print(type(conn))

# Create table
cr=conn.execute('''CREATE TABLE COMPANY
         (ID INT PRIMARY KEY     NOT NULL,
         NAME           TEXT    NOT NULL,
         AGE            INT     NOT NULL,
         ADDRESS        CHAR(50),
         SALARY         REAL);''')
print ("Table created successfully");
print(cr)
conn.close()

<class 'sqlite3.Connection'>
Table created successfully
<sqlite3.Cursor object at 0x7b461b548d40>

In [ ]:
# Insert values
conn = sqlite3.connect('test.db')
cr=conn.cursor()
# instead of cr we use conn directly
cr.execute('''INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (1, 'Paul', 32, 'California', 20000.00 )''')
conn.execute("INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS,SALARY) \
      VALUES (2, 'Allen', 25, 'Texas', 15000.00 )")
conn.execute("INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS,SALARY) \
      VALUES (3, 'Teddy', 23, 'Norway', 20000.00 )")

a=4
b='Mark'
c=25
d='Rich-Mond'
e=65000
cr.execute("INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS,SALARY) \
      VALUES (?, ?, ?, ?, ? )",(a,b,c,d,e))
conn.commit()
print ("Records created successfully")
conn.close()

Records created successfully

In [ ]:
# Fetch values
conn = sqlite3.connect('test.db')
print ("Opened database successfully");
cursor = conn.execute("SELECT id, name, address, salary from COMPANY")
# can also call exeutescript()
print(type(cursor))
for row in cursor: # can also use fetchmany(), fetchone() etc.
   print ("ID = ", row[0])
   print ("NAME = ", row[1])
   print ("ADDRESS = ", row[2])
   print ("SALARY = ", row[3], "\n")
print ("Rows fetched successfully")
x=3
cursor = conn.execute("SELECT id, name, address, salary from COMPANY where id=?",(x,))
for row in cursor:
   print(row)
   print ("ID = ", row[0])
   print ("NAME = ", row[1])
   print ("ADDRESS = ", row[2])
   print ("SALARY = ", row[3], "\n")
print ("1 row fetched successfully")
conn.close()

Opened database successfully
<class 'sqlite3.Cursor'>
ID =  1
NAME =  Paul
ADDRESS =  California
SALARY =  20000.0

ID =  2
NAME =  Allen
ADDRESS =  Texas
SALARY =  15000.0

ID =  3
NAME =  Teddy
ADDRESS =  Norway
SALARY =  20000.0

ID =  4
NAME =  Mark
ADDRESS =  Rich-Mond
SALARY =  65000.0

Rows fetched successfully
(3, 'Teddy', 'Norway', 20000.0)
ID =  3
NAME =  Teddy
ADDRESS =  Norway
SALARY =  20000.0

1 row fetched successfully

In [ ]:
# Update values
conn = sqlite3.connect('test.db')
print ("Opened database successfully");
temp=conn.execute("UPDATE COMPANY set SALARY = 25000.00 where ID = 1")
print(temp)
conn.commit()
print ("Total number of rows updated :", conn.total_changes)
cursor = conn.execute("SELECT id, name, address, salary from COMPANY")
for row in cursor:
   print ("ID = ", row[0])
   print ("NAME = ", row[1])
   print ("ADDRESS = ", row[2])
   print ("SALARY = ", row[3], "\n")
print ("Results shown successfully");
conn.close()

Opened database successfully
<sqlite3.Cursor object at 0x7b2711086d40>
Total number of rows updated : 1
ID =  1
NAME =  Paul
ADDRESS =  California
SALARY =  25000.0

ID =  2
NAME =  Allen
ADDRESS =  Texas
SALARY =  15000.0

ID =  3
NAME =  Teddy
ADDRESS =  Norway
SALARY =  20000.0

ID =  4
NAME =  Mark
ADDRESS =  Rich-Mond
SALARY =  65000.0

Results shown successfully

In [ ]:
# Delete values
conn = sqlite3.connect('test.db')
print ("Opened database successfully");
x=2
conn.execute("DELETE from COMPANY where ID = ?",(x,))
conn.commit()
print ("Total number of rows deleted :", conn.total_changes)
cursor = conn.execute("SELECT id, name, address, salary from COMPANY")
for row in cursor:
   print ("ID = ", row[0])
   print ("NAME = ", row[1])
   print ("ADDRESS = ", row[2])
   print ("SALARY = ", row[3], "\n")
print ("Deletion done successfully");
conn.close()

Opened database successfully
Total number of rows deleted : 1
ID =  1
NAME =  Paul
ADDRESS =  California
SALARY =  25000.0

ID =  3
NAME =  Teddy
ADDRESS =  Norway
SALARY =  20000.0

ID =  4
NAME =  Mark
ADDRESS =  Rich-Mond
SALARY =  65000.0

Deletion done successfully

In [ ]:
import pandas as pd
conn = sqlite3.connect('test.db')
# dataframe is a structure to hold tabular data
df = pd.read_sql_query("select * from COMPANY", conn)

df.head()

   ID   NAME  AGE     ADDRESS   SALARY
0   1   Paul   32  California  20000.0
1   2  Allen   25       Texas  15000.0
2   3  Teddy   23      Norway  20000.0
3   4   Mark   25   Rich-Mond  65000.0

**You can do similar things with other data sources like PostgreSQL etc.**

https://www.tutorialspoint.com/postgresql/postgresql_python.htm



---

**Regular expressions**

Quite an exhaustive subject.............

https://www.w3schools.com/python/python_regex.asp

https://www.regular-expressions.info/

In [ ]:
import re

txt = "The rain in Spain"

# it will return a Match object if the pattern is found. otherwise it will return None
x = re.search("^The.*Spain$", txt)

if (x):
  print(type(x))
  print("YES! We have a match!")
else:
  print("No match")

<class 're.Match'>
YES! We have a match!

**Slice object**

In [ ]:
# slice object
a = ("a", "b", "c", "d", "e", "f", "g", "h")
x = slice(3,7,2) # 3 to 7 indices, skip by 2
print(x)
print(a[x])

slice(3, 7, 2)
('d', 'f')

**Lambda functions**

* A lambda function is an anonymous inline function. It is defined without a name. This can be used if you need a nameless function for a short period of time.  Can work with single expression only

In [ ]:
fun = lambda a, b : a * b
print(fun(5, 6))

30

**List Comprehension**

* List comprehensions are used for creating new lists from other iterables.
* As list comprehensions return lists, they consist of brackets containing the expression, which is executed for each element along with the for to iterate over each element.

In [ ]:
numbers = (1, 2, 3, 4)

squares = [n**2 for n in numbers if n%2==0]

print(squares)

[4, 16]

**Iterators**

* An iterator is an object that can be iterated upon, meaning that you can traverse through all the values.
* To create an object/class as an iterator you have to implement the methods __iter__() and __next__() to your object.

In [ ]:
class MyNumbers:
  def __init__(self,limit,step):
    self.limit=limit
    self.step=step

  def __iter__(self):
    print('iter')
    self.a = 1
    return self

  def __next__(self):
    if self.a <= self.limit:
      print('next')
      x = self.a
      self.a += self.step
      return x
    else:
      raise StopIteration

myObj = MyNumbers(10,2)
for n in myObj:
  print(n)

iter
next
1
next
3
next
5
next
7
next
9

**Working with JSON**

* JSON is a syntax for storing and exchanging data.
* It is a standardized format people use to pass data around. XML is similar.

* JavaScript Object Notation was inspired by a subset of the JavaScript
* It’s easy for both humans and machines to create and understand.

* The process of encoding JSON is called serialization.
* It is the transformation of data into a series of bytes to be stored or transmitted across a network.
* Deserialization is the reverse process.

* The json library in Python exposes the dump() method for writing data to files and dumps() method for writing to a Python string.

* json library has load() and loads() for turning JSON encoded data into Python objects.

* https://www.digitalocean.com/community/tutorials/an-introduction-to-json

In [ ]:
df.set_index('ID', inplace=True)
df.head()

     NAME  AGE     ADDRESS   SALARY
ID
1    Paul   32  California  20000.0
2   Allen   25       Texas  15000.0
3   Teddy   23      Norway  20000.0
4    Mark   25   Rich-Mond  65000.0

In [ ]:
df.to_json('js.json')

In [ ]:
data={
    "firstName": "Alex",
    "lastName": "Smith",
    "age": 35,
    "children": [
        {
            "firstName": "Alice",
            "age": 6
        },
        {
            "firstName": "Bob",
            "age": 8
        }
    ]
}

import json
# Write JSON
with open("data_file.json", "w") as write_file:
    json.dump(data, write_file)

json_string = json.dumps(data)
print(json_string)

{"firstName": "Alex", "lastName": "Smith", "age": 35, "children": [{"firstName": "Alice", "age": 6}, {"firstName": "Bob", "age": 8}]}

In [ ]:
# Read JSON
with open("data_file.json", "r") as read_file:
    read_data = json.load(read_file)

read_data_str = json.loads(json_string)

print(type(read_data_str))
print(read_data_str["age"])

<class 'dict'>
35

* We will use JSONPlaceholder, a source of fake JSON data for practice purpose explore the data in the url
* We need to make an API request to the JSONPlaceholder service, so just use the requests package

* The requests module allows you to send HTTP requests using Python.
* The HTTP request returns a Response Object with all the  response data (content, encoding, status, etc)

In [ ]:
import json
import requests

response = requests.get("https://jsonplaceholder.typicode.com/todos")
todos = json.loads(response.text)
print(type(todos))
print(todos[:3])

count=0
for todo in todos:
    if todo["completed"]:
        # Increment the existing user's count.
        count+= 1
print(count)

<class 'list'>
[{'userId': 1, 'id': 1, 'title': 'delectus aut autem', 'completed': False}, {'userId': 1, 'id': 2, 'title': 'quis ut nam facilis et officia qui', 'completed': False}, {'userId': 1, 'id': 3, 'title': 'fugiat veniam minus', 'completed': False}]
90

In [ ]:
import pandas as pd

with open("data_file_new.json", "w") as write_file:
    json.dump(todos, write_file)

In [ ]:
df = pd.read_json('data_file_new.json')
df.head()

   userId  id                                              title  completed
0       1   1                                 delectus aut autem      False
1       1   2                 quis ut nam facilis et officia qui      False
2       1   3                                fugiat veniam minus      False
3       1   4                                   et porro tempora       True
4       1   5  laboriosam mollitia et enim quasi adipisci qui...      False